/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.map.cadastroproduto.view;

import br.edu.map.cadastroproduto.dao.ProdutoDAO;
import br.edu.map.cadastroproduto.model.Produto;
import br.edu.map.cadastroproduto.util.RelatorioManager;
import br.edu.map.cadastroproduto.util.StringsUtil;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Pichau
 */
public class ProdutosJFrame extends javax.swing.JFrame {
    
    private ProdutoDAO dao = new ProdutoDAO();
    private Produto produtoSelecionado;

    /**
     * Creates new form ProdutosJFrame
     */
    public ProdutosJFrame() {
        initComponents();
        preencherTabela(null);
        setPropiedades();
    }
    
    public void preencherTabela(List<Produto> param){
        
        try {

            List<Produto> lista = (param == null) ? dao.listarProdutos() : param;

            DefaultTableModel model = new DefaultTableModel();

            model.setColumnCount(7);
            model.setColumnIdentifiers(new String[]{StringsUtil.getString(StringsUtil.COLUNA_CODIGO), StringsUtil.getString(StringsUtil.COLUNA_NOME), StringsUtil.getString(StringsUtil.COLUNA_PRECO), StringsUtil.getString(StringsUtil.COLUNA_FABRICANTE), StringsUtil.getString(StringsUtil.COLUNA_SISTEMA), StringsUtil.getString(StringsUtil.COLUNA_COR), StringsUtil.getString(StringsUtil.COLUNA_DETALHES)});
            model.setRowCount(lista.size());

            for (int i = 0; i < lista.size(); i++) {
                model.setValueAt(lista.get(i).getCodigo(), i, 0);
                model.setValueAt(lista.get(i).getNome(), i, 1);
                model.setValueAt(lista.get(i).getPreco(), i, 2);
                model.setValueAt(lista.get(i).getEspc().getFabricante(), i, 3);
                model.setValueAt(lista.get(i).getEspc().getSistema(), i, 4);
                model.setValueAt(lista.get(i).getEspc().getCor(), i, 5);
                model.setValueAt(lista.get(i).getEspc().getDetalhes(), i, 6);
            }

            tableProdutos.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void setPropiedades(){
        
        labelProdutos.setText(StringsUtil.getString(StringsUtil.TITULO_PRODUTO));
        buttonNovo.setText(StringsUtil.getString(StringsUtil.BOTAO_NOVO));
        buttonEditar.setText(StringsUtil.getString(StringsUtil.BOTAO_EDITAR));
        buttonExcluir.setText(StringsUtil.getString(StringsUtil.BOTAO_EXCLUIR));
        buttonSair.setText(StringsUtil.getString(StringsUtil.BOTAO_SAIR));
        menuIdioma.setText(StringsUtil.getString(StringsUtil.MENU_IDIOMA));
        menuRelatorios.setText(StringsUtil.getString(StringsUtil.MENU_RELATORIO));
        menuItemRelatorioGeral.setText(StringsUtil.getString(StringsUtil.MENUITEM_RELATORIOGERAL));
        menuItemPreto.setText(StringsUtil.getString(StringsUtil.MENUITEM_RELATORIOCORPRETA));
        menuItemMilmais.setText(StringsUtil.getString(StringsUtil.MENUITEM_RELATORIOPRECOMIL));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProdutos = new javax.swing.JLabel();
        textBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIdioma = new javax.swing.JMenu();
        menuItemPTBR = new javax.swing.JMenuItem();
        menuItemENUS = new javax.swing.JMenuItem();
        menuItemESES = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuItemRelatorioGeral = new javax.swing.JMenuItem();
        menuItemMilmais = new javax.swing.JMenuItem();
        menuItemPreto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelProdutos.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        labelProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProdutos.setText("PRODUTOS");
        labelProdutos.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        textBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textBuscaKeyReleased(evt);
            }
        });

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProdutos);

        buttonNovo.setText("Novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        menuIdioma.setText("Idiomas");

        menuItemPTBR.setText("pt_BR");
        menuItemPTBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPTBRActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemPTBR);

        menuItemENUS.setText("en_US");
        menuItemENUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemENUSActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemENUS);

        menuItemESES.setText("es_ES");
        menuItemESES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemESESActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemESES);

        jMenuBar1.add(menuIdioma);

        menuRelatorios.setText("Relatórios");

        menuItemRelatorioGeral.setText("Relatório Geral");
        menuItemRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioGeralActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemRelatorioGeral);

        menuItemMilmais.setText("Preço: 1000+");
        menuItemMilmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMilmaisActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemMilmais);

        menuItemPreto.setText("Cor: Preto");
        menuItemPreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuItemPreto);

        jMenuBar1.add(menuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textBusca)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(labelProdutos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        // TODO add your handling code here:
        
        produtoSelecionado = null;
        NovoProdutoJFrame janelaNovoP = new NovoProdutoJFrame(this);
        janelaNovoP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janelaNovoP.setPropiedades(produtoSelecionado);
        janelaNovoP.setVisible(true);
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        // TODO add your handling code here:
        
        if(produtoSelecionado == null){
            
            JOptionPane.showMessageDialog(this, StringsUtil.getString(StringsUtil.AVISO_SELECPRODUTO));
        }else{
            
            NovoProdutoJFrame janelaNovoP = new NovoProdutoJFrame(this, produtoSelecionado);
            janelaNovoP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            janelaNovoP.setPropiedades(produtoSelecionado);
            janelaNovoP.preencherProduto();
            janelaNovoP.setVisible(true);
        }
        
        
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        // TODO add your handling code here:
        
        if (produtoSelecionado != null) {
            try {

                int op = JOptionPane.showConfirmDialog(this, StringsUtil.getString(StringsUtil.AVISO_EXCLUIR), StringsUtil.getString(StringsUtil.BOTAO_EXCLUIR) , JOptionPane.OK_CANCEL_OPTION);
                if (op == JOptionPane.OK_OPTION) {
                    dao.removerProduto(produtoSelecionado);
                    preencherTabela(null);
                    produtoSelecionado = null;
                }

            } catch (Exception ex) {

            }
        } else {
            JOptionPane.showMessageDialog(this, StringsUtil.getString(StringsUtil.AVISO_SELECPRODUTO));
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_buttonSairActionPerformed

    private void textBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscaKeyReleased
        // TODO add your handling code here:
        
        String busca = textBusca.getText();

        try {
            List<Produto> resultado = dao.buscarProduto(busca);
            preencherTabela(resultado);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_textBuscaKeyReleased

    private void tableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseClicked
        // TODO add your handling code here:
        
        int row = tableProdutos.rowAtPoint(evt.getPoint());

        int codigo = (int) tableProdutos.getModel().getValueAt(row, 0);

        try {
            produtoSelecionado = dao.buscarProduto(codigo);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableProdutosMouseClicked

    private void menuItemPTBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPTBRActionPerformed
        // TODO add your handling code here:
        
        StringsUtil.setLocale(StringsUtil.LOCALE_PT_BR);
        setPropiedades();
        preencherTabela(null);
    }//GEN-LAST:event_menuItemPTBRActionPerformed

    private void menuItemENUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemENUSActionPerformed
        // TODO add your handling code here:
        
        StringsUtil.setLocale(StringsUtil.LOCALE_EN_US);
        setPropiedades();
        preencherTabela(null);
    }//GEN-LAST:event_menuItemENUSActionPerformed

    private void menuItemESESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemESESActionPerformed
        // TODO add your handling code here:
        
        StringsUtil.setLocale(StringsUtil.LOCALE_ES_ES);
        setPropiedades();
        preencherTabela(null);
    }//GEN-LAST:event_menuItemESESActionPerformed

    private void menuItemRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioGeralActionPerformed
        // TODO add your handling code here:
        
        try {
            
            JasperPrint relatorio = RelatorioManager.gerarRelatorioProdutos(dao.listarProdutos());
            JFrame frame = new JFrame();
            frame.setSize(800, 600);
            JRViewer viewer = new JRViewer(relatorio);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            frame.add(viewer);
            frame.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ProdutosJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemRelatorioGeralActionPerformed

    private void menuItemMilmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMilmaisActionPerformed
        // TODO add your handling code here:
        
        try {

            JasperPrint relatorio = RelatorioManager.gerarRelatorioProdutos(dao.listarProdutosMilMais());
            JFrame frame = new JFrame();
            frame.setSize(800, 600);
            JRViewer viewer = new JRViewer(relatorio);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            frame.add(viewer);
            frame.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ProdutosJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemMilmaisActionPerformed

    private void menuItemPretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretoActionPerformed
        // TODO add your handling code here:
        
        try {

            JasperPrint relatorio = RelatorioManager.gerarRelatorioProdutos(dao.listarProdutosCorPreta());
            JFrame frame = new JFrame();
            frame.setSize(800, 600);
            JRViewer viewer = new JRViewer(relatorio);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            frame.add(viewer);
            frame.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ProdutosJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemPretoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

            java.util.logging.Logger.getLogger(ProdutosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelProdutos;
    private javax.swing.JMenu menuIdioma;
    private javax.swing.JMenuItem menuItemENUS;
    private javax.swing.JMenuItem menuItemESES;
    private javax.swing.JMenuItem menuItemMilmais;
    private javax.swing.JMenuItem menuItemPTBR;
    private javax.swing.JMenuItem menuItemPreto;
    private javax.swing.JMenuItem menuItemRelatorioGeral;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField textBusca;
    // End of variables declaration//GEN-END:variables
}
